-- MySQL Script generated by MySQL Workbench
-- Sun 08 Apr 2018 05:49:58 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cruddemo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cruddemo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cruddemo` DEFAULT CHARACTER SET utf8 ;
USE `cruddemo` ;

-- -----------------------------------------------------
-- Table `cruddemo`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruddemo`.`Game` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `developer` VARCHAR(100) NOT NULL,
  `publisher` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` TEXT NOT NULL,
  `image` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cruddemo`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruddemo`.`User` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `address` VARCHAR(128) NULL DEFAULT NULL,
  `gamertag` VARCHAR(100) NOT NULL,
  `profile_picture` VARCHAR(256) NULL DEFAULT 'test',
  `password` VARCHAR(128) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cruddemo`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cruddemo`.`Transaction` (
  `order_number` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `game_id` INT(11) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'confirmed',
  `total` FLOAT NOT NULL,
  PRIMARY KEY (`order_number`),
  INDEX `fk_Order_User_idx` (`user_id` ASC),
  INDEX `fk_Order_Game1_idx` (`game_id` ASC),
  CONSTRAINT `fk_Order_Game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `cruddemo`.`Game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `cruddemo`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
